"""Image generation tool -- local Qwen-Image (default) or OpenAI DALL-E."""

from __future__ import annotations

import os
import re
import subprocess
import time
import uuid
from pathlib import Path
from typing import Any

from openjarvis.core.registry import ToolRegistry
from openjarvis.core.types import ToolResult
from openjarvis.tools._stubs import BaseTool, ToolSpec

_SIZE_RE = re.compile(r"^\d{3,4}x\d{3,4}$")
_LOCAL_GOVERNOR = "/srv/media-gen/bin/media-gen-governor-jarvis-image.sh"
_MEDIA_IMAGES_DIR = Path("/srv/media-gen/images")
_LOCAL_TIMEOUT_SECONDS = 900  # Qwen-Image at 40 steps can take several minutes


def _media_output_path(
    output_path: str | None, media_dir: Path, extension: str
) -> Path:
    """Resolve `output_path` (a model-supplied argument) to a path inside
    *media_dir*, never outside it.

    `output_path` is only ever treated as a filename, not a full path: a
    value like "../../../home/user/.ssh/authorized_keys" or an absolute
    path would otherwise let the model write generated bytes anywhere on
    disk the process can reach. Taking just the basename also keeps the
    returned /jarvis-media/... URL honest -- it always points at the file
    that was actually written, instead of silently pointing at the media
    dir while the real file landed somewhere else entirely.
    """
    media_dir.mkdir(parents=True, exist_ok=True)
    if output_path:
        name = Path(output_path).name
        if name and name not in (".", ".."):
            return media_dir / name
    return (
        media_dir / f"jarvis-gen-{int(time.time())}-{uuid.uuid4().hex[:8]}{extension}"
    )


@ToolRegistry.register("image_generate")
class ImageGenerateTool(BaseTool):
    """Generate images from text descriptions.

    Default provider is 'local': a full-quality Qwen-Image diffusion model
    running on-device via stable-diffusion.cpp (see
    media-gen-governor-jarvis-image.sh) -- much higher fidelity than a
    turbo/distilled model, at the cost of taking minutes instead of seconds.
    Provider 'openai' remains available if OPENAI_API_KEY is configured.
    """

    tool_id = "image_generate"
    is_local = True

    @property
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="image_generate",
            description=(
                "Generate an image from a text description using a local, "
                "full-quality diffusion model (Qwen-Image). Takes 2-6 "
                "minutes to run -- say so if the user is waiting. Returns "
                "markdown of the form ![alt](/jarvis-media/images/...) -- "
                "you MUST copy that markdown into your reply to the user "
                "EXACTLY as returned (do not paraphrase, describe, or omit "
                "it) so the image actually renders; add at most a short "
                "sentence before or after it."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "Text description of the image to generate.",
                    },
                    "size": {
                        "type": "string",
                        "description": (
                            "Image size as WIDTHxHEIGHT, e.g. '1024x1024', "
                            "'1024x576' (landscape), '576x1024' (portrait). "
                            "Default '1024x1024'."
                        ),
                    },
                    "output_path": {
                        "type": "string",
                        "description": "Optional file path to save the image to.",
                    },
                    "provider": {
                        "type": "string",
                        "description": (
                            "'local' (default, on-device Qwen-Image) or "
                            "'openai' (DALL-E, needs OPENAI_API_KEY)."
                        ),
                    },
                },
                "required": ["prompt"],
            },
            category="media",
            timeout_seconds=950,
        )

    def execute(self, **params: Any) -> ToolResult:
        prompt = params.get("prompt", "")
        if not prompt:
            return ToolResult(
                tool_name="image_generate",
                content="No prompt provided.",
                success=False,
            )

        provider = params.get("provider") or "local"
        size = params.get("size", "1024x1024")

        if provider == "local":
            return self._execute_local(prompt, size, params.get("output_path"))
        if provider == "openai":
            return self._execute_openai(prompt, size, params.get("output_path"))
        return ToolResult(
            tool_name="image_generate",
            content=f"Unsupported provider '{provider}'. Use 'local' or 'openai'.",
            success=False,
        )

    def _execute_local(
        self, prompt: str, size: str, output_path: str | None
    ) -> ToolResult:
        if not _SIZE_RE.match(size):
            size = "1024x1024"

        if not Path(_LOCAL_GOVERNOR).exists():
            return ToolResult(
                tool_name="image_generate",
                content=(
                    f"Local image generation is not set up on this host "
                    f"({_LOCAL_GOVERNOR} missing)."
                ),
                success=False,
            )

        outfile = str(_media_output_path(output_path, _MEDIA_IMAGES_DIR, ".png"))

        try:
            proc = subprocess.run(
                [_LOCAL_GOVERNOR, prompt, size, outfile],
                capture_output=True,
                text=True,
                timeout=_LOCAL_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            return ToolResult(
                tool_name="image_generate",
                content=(
                    f"Image generation timed out after {_LOCAL_TIMEOUT_SECONDS}s."
                ),
                success=False,
            )
        except Exception as exc:
            return ToolResult(
                tool_name="image_generate",
                content=f"Failed to run local image generation: {exc}",
                success=False,
            )

        if proc.returncode != 0 or not Path(outfile).is_file():
            tail = "\n".join((proc.stdout or "").splitlines()[-15:])
            return ToolResult(
                tool_name="image_generate",
                content=(
                    f"Local image generation failed (exit {proc.returncode}). "
                    f"Last log lines:\n{tail}"
                ),
                success=False,
            )

        filename = Path(outfile).name
        url = f"/jarvis-media/images/{filename}"

        # IMPORTANT: do NOT embed the image as a base64 data URI here. The
        # tool result content is fed back into the LLM's context by the
        # orchestrator's function-calling loop -- a ~1-2MB base64 PNG blows
        # past kat-coder-v2.5's 262144-token context window by an order of
        # magnitude (observed: 1.7M+ tokens -> hard 400 from the router,
        # surfaced as a 500 to the chat client). Returning just the relative
        # URL keeps the tool result tiny; the model includes it as a normal
        # markdown image reference and the frontend/browser fetches the
        # actual bytes from the /jarvis-media/images/ static route.
        alt = prompt.replace("[", "").replace("]", "")[:120]
        content = f"![{alt}]({url})"

        return ToolResult(
            tool_name="image_generate",
            content=content,
            success=True,
            metadata={"path": outfile, "url": url, "size": size, "provider": "local"},
        )

    def _execute_openai(
        self, prompt: str, size: str, output_path: str | None
    ) -> ToolResult:
        valid_sizes = {"256x256", "512x512", "1024x1024"}
        if size not in valid_sizes:
            return ToolResult(
                tool_name="image_generate",
                content=(
                    f"Invalid size '{size}' for OpenAI provider."
                    f" Must be one of: {', '.join(sorted(valid_sizes))}."
                ),
                success=False,
            )

        try:
            import openai
        except ImportError:
            return ToolResult(
                tool_name="image_generate",
                content=(
                    "openai package not installed. Install with: pip install openai"
                ),
                success=False,
            )

        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            return ToolResult(
                tool_name="image_generate",
                content="No API key configured. Set OPENAI_API_KEY.",
                success=False,
            )

        try:
            client = openai.OpenAI()
            response = client.images.generate(
                model="dall-e-3",
                prompt=prompt,
                size=size,
                n=1,
            )
            url = response.data[0].url
        except Exception as exc:
            return ToolResult(
                tool_name="image_generate",
                content=f"Image generation error: {exc}",
                success=False,
            )

        if output_path:
            try:
                import httpx

                resp = httpx.get(url, follow_redirects=True, timeout=60.0)
                resp.raise_for_status()
                saved_to = _media_output_path(output_path, _MEDIA_IMAGES_DIR, ".png")
                saved_to.write_bytes(resp.content)
            except Exception as exc:
                return ToolResult(
                    tool_name="image_generate",
                    content=(f"Image generated but failed to save: {exc}. URL: {url}"),
                    success=False,
                    metadata={"url": url, "size": size, "provider": "openai"},
                )

        return ToolResult(
            tool_name="image_generate",
            content=url,
            success=True,
            metadata={"url": url, "size": size, "provider": "openai"},
        )


__all__ = ["ImageGenerateTool"]
